#!/bin/bash

echo "Fixing WebRTC dependency issue..."

echo ""
echo "Please follow these steps in Xcode:"
echo ""
echo "1. Open Xcode and open your Faith Journal project"
echo "2. Go to File > Add Package Dependencies..."
echo "3. Enter this URL: https://github.com/stasel/WebRTC"
echo "4. Click 'Add Package'"
echo "5. When prompted, select the 'Faith Journal' target"
echo "6. Click 'Add Package'"
echo ""
echo "If that doesn't work, try this alternative:"
echo "1. Go to File > Add Package Dependencies..."
echo "2. Enter URL: https://github.com/WebRTC/WebRTC"
echo "3. Or try: https://github.com/webrtc-sdk/Specs"
echo ""
echo "After adding the package:"
echo "1. Go to File > Packages > Reset Package Caches"
echo "2. Go to File > Packages > Resolve Package Versions"
echo "3. Clean Build Folder (Shift+Cmd+K)"
echo "4. Build the project (Cmd+B)"
echo ""
echo "If you still get errors, you can temporarily comment out the WebRTC imports"
echo "in the live streaming files until we get the dependency working."

# Open Xcode
open "Faith Journal/Faith Journal.xcodeproj" 