#!/bin/bash

echo "🔐 Agora App Certificate Retrieval Guide"
echo "=========================================="
echo ""
echo "I cannot access your Agora account, but here's how to get it:"
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1. Open your web browser"
echo "2. Go to: https://console.agora.io/"
echo "3. Sign in to your Agora account"
echo "4. In the dashboard, find your project (or create one if needed)"
echo "5. Click on your project name to open it"
echo "6. Click the 'Edit' button (usually at the top right)"
echo "7. Scroll down to find 'App Certificate'"
echo "8. Click 'Show' or 'Copy' next to the App Certificate"
echo "9. Copy the certificate value (it's a long string)"
echo ""
echo "💡 Quick Link:"
echo "   https://console.agora.io/"
echo ""
echo "📝 Once you have the certificate, set it with:"
echo "   export AGORA_APP_CERTIFICATE=\"your-certificate-here\""
echo ""
echo "🔍 Your App ID (already configured):"
echo "   89fdd88c9b594cf0947a48a8730e5f62"
echo ""
echo "⚠️  Note: The App Certificate is different from the App ID"
echo "   - App ID: Public identifier (already set)"
echo "   - App Certificate: Secret key for token generation (needed now)"
echo ""
